module.exports = {
  tabWidth: 2,
  printWidth: 120,
  semi: false,
  singleQuote: true,
  endOfLine: 'lf',
  arrowParens: 'always',
  jsxSingleQuote: true,
  importOrder: [
    '^[./]?(react|@?next)',
    '<THIRD_PARTY_MODULES>',
    '^(.*)/store/hooks$',
    '^(src/store|store)/(.*)/actions$',
    '^(src/store|store)/(.*)/selectors$',
    '^hooks/(.*)$',
    '^(src/pageContainers|pageContainers)/(.*)$',
    '^(src/containers|containers)/(.*)$',
    '^(src/components|components)/(.*)$',
    '^(src/dialogs|dialogs)/(.*)$',
    '^utils/(.*)$',
    '(.*).scss',
    '^types/(.*)$',
    '^translates/(.*)$',
    '^(src/config|config)/(.*)$',
    '^analyticActions/(.*)$',
    '^(src/services|services)/(.*)$',
    '^[./]',
  ],
  importOrderSortSpecifiers: true,
}
